# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: brettt89/silverstripe-web
        environment:
          - SS_DATABASE_CLASS=MySQLPDODatabase
          - SS_DATABASE_SERVER=127.0.0.1
          - SS_DATABASE_USERNAME=root
          - SS_DATABASE_PASSWORD=ubuntu
          - SS_DATABASE_NAME=circle_test
          - SS_ENVIRONMENT_TYPE=dev
          - JWT_PREFIX=jwt_
          - JWT_SIGNER_KEY=test_signer
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_DATABASE=circle_test
          - MYSQL_HOST=127.0.0.1

    working_directory: ~/var/www

    branches:
      only:
        - master
        - develop
        - /feature.*/

    steps:
      # Install additional requirements
      - run:
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php --install-dir=/usr/local/bin --filename=composer
            php -r "unlink('composer-setup.php');"

      - run: composer create-project silverstripe/installer:dev-master ~/var/www -n
      - run: composer require axyr/silverstripe-ideannotator:dev-master -n
      - run: rm phpunit.xml.dist
      - run: cp ideannotator/phpunit.xml.dist .
      - run: vendor/silverstripe/framework/sake dev/build

      # run tests!
      - run: vendor/bin/phpunit ideannotator/tests -d memory_limit=512M
